# -----------------------------------------------------------------------------
# Forked from https://raw.githubusercontent.com/opencontainers/runc/2888e6e54339e52ae45710daa9e47cdb2e1926f9/.github/dependabot.yml
# Copyright The runc Authors.
# Licensed under the Apache License, Version 2.0
# -----------------------------------------------------------------------------

# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Dependencies listed in go.mod
  - package-ecosystem: "gomod"
    ignore:
      - dependency-name: "github.com/containerd/errdefs"
        update-types: ["version-update:semver-minor"]
    directory: "/"  # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      golang-x:
        patterns:
          - "golang.org/x/*"
      moby-sys:
        patterns:
          - "github.com/moby/sys/*"
      docker:
        patterns:
          - "github.com/docker/docker"
          - "github.com/docker/cli"
      containerd:
        patterns:
          - "github.com/containerd/containerd"
          - "github.com/containerd/containerd/api"
      stargz:
        patterns:
          - "github.com/containerd/stargz-snapshotter"
          - "github.com/containerd/stargz-snapshotter/estargz"
          - "github.com/containerd/stargz-snapshotter/ipfs"

  # Dependencies listed in .github/workflows/*.yml
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Dependencies listed in Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
